import os

ADDRESS = os.getenv('ADDRESS', 'localhost')
PORT = int(os.getenv('PORT', 8000))
ALEXA_VOICE_SERVICE_CLIENT_ID = os.environ['ALEXA_VOICE_SERVICE_CLIENT_ID']
ALEXA_VOICE_SERVICE_CLIENT_SECRET = os.environ[
	'ALEXA_VOICE_SERVICE_CLIENT_SECRET'
]
ALEXA_VOICE_SERVICE_DEVICE_TYPE_ID = os.environ[
	'ALEXA_VOICE_SERVICE_DEVICE_TYPE_ID'
]
